### ISSUE TITLE
Invalid Syntax after install

### ISSUE THREAD

**Issue by bustamantenathan** [GLolol/obmenu#1]
After install (with pipe menus) attempting to start obmenu it yeilds the error 

```
    SyntaxError: invalid syntax
```

anyway to get around this. The errors appears on line 60 

```
    File "./obmenu", line 60
       def _change_id(self, model, path, it,(old_id, new_id)):
```

**Comment by jlu5** [comment]
What version of Python are you running with?

**Comment by bustamantenathan** [comment]
Pyhon 3.4.3
